apiVersion: configsync.gke.io/v1beta1
kind: RootSync
metadata:
  name: platformrootconfig
  namespace: config-management-system
spec:
  sourceFormat: unstructured
  git:
   repo: https://github.com/guid1984/acm-platform-root.git
   revision: HEAD
   branch: staging
   auth: none
