#/non-production/sector-1/kustomization.yaml
# specify resources to be synced or rendered
resources:
- "root-configurations/ciso" # setup root sync object for ciso
- "root-configurations/platform" # setup root sync object for platform
