apiVersion: configsync.gke.io/v1beta1
kind: RootSync
metadata:
  name: platform_root_repo
  namespace: config-management-system
spec:
  sourceFormat: unstructured
  git:
   repo: https://github.com/guid1984/acm-platform-root.git
     revision: HEAD
     branch: main
     auth: none
